format = "[](bold white) $all"
command_timeout = 1000 # 1s

[directory]
style = "bold green"

# Disable battery until this issue is fixed
# https://github.com/starship/starship/issues/5350
[battery]
disabled = true

[aws]
symbol = " "

[kubernetes]
disabled = true

[git_branch]
style = "bold yellow"
symbol = ""

[git_status]
style = "bold gray"
format = '[$all_status$ahead_behind]($style) '
ahead = "[${count}](bold yellow)"
diverged = "󰵉${ahead_count} ${behind_count}"
behind = "${count}"
renamed = "󰈑${count}"
modified = "[${count}](bold blue)"
untracked = "[?${count}](bold blue)"
staged = "[${count}](bold green)"

[git_commit]
disabled = true

[golang]
symbol = " "

[terraform]
symbol = "󱁢 "
format = "via [$symbol]($style)"

[lua]
symbol = " "
