format = "[](bold white) $all"
command_timeout = 1000 # 1s

[directory]
style = "bold green"

[hostname]
style = "bold yellow"
format = "[$ssh_symbol$hostname]($style) on "
ssh_symbol = "󰛳 "

[aws]
symbol = " "

[kubernetes]
disabled = true

[git_branch]
style = "bold yellow"
symbol = ""

[git_status]
style = "bold gray"
format = '[$all_status$ahead_behind]($style) '
ahead = "[${count}](bold yellow)"
diverged = "󰵉${ahead_count} ${behind_count}"
behind = "${count}"
renamed = "󰈑${count}"
modified = "[${count}](bold blue)"
untracked = "[?${count}](bold blue)"
staged = "[${count}](bold green)"

[git_commit]
disabled = true

[golang]
symbol = " "

[terraform]
symbol = "󱁢 "
format = "via [$symbol]($style)"

[lua]
symbol = " "
